#!/bin/sh
#
# The following path detection code is copied from StackOverflow [1]. It is 
# licensed under GPL 2.0. 
#
# [1]: <http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in/179231#179231>. 


SCRIPT_PATH="${BASH_SOURCE[0]}"
if([ -h "${SCRIPT_PATH}" ]) then
  while([ -h "${SCRIPT_PATH}" ]) do SCRIPT_PATH=`readlink "${SCRIPT_PATH}"`; done
fi
pushd . > /dev/null
cd `dirname ${SCRIPT_PATH}` > /dev/null
SCRIPT_PATH=`pwd`;
popd  > /dev/null


#echo $SCRIPT_PATH



link_file() 
{
    if [ -h ~/$1 ]; then
        # symlink already exists. backup the old symlink and replace it
        if [ "$(readlink ~/$1)" != "$SCRIPT_PATH/files/$1" ]; then
            mv ~/$1 ~/$1.old
            ln -s $SCRIPT_PATH/files/$1  ~/$1 
            echo ~/$1 installed.
        fi
    elif [ -f ~/$1 ]; then
        # file already exists. backup it and symlink to the new one
        mv ~/$1 ~/$1.old
        ln -s $SCRIPT_PATH/files/$1  ~/$1 
        echo ~/$1 installed.
    else
        # file not exists. symlink
        ln -s $SCRIPT_PATH/files/$1  ~/$1 
        echo ~/$1 installed.
    fi
}


for each in $SCRIPT_PATH/files/.*; do
    if [ -f $each ]; then
        link_file `basename $each` 
    fi
done

