#!/bin/bash

# exit bash if any command fails
set -e

if [ -z $1 ]; then
    DOTFILES=~/.dotfiles
else
    DOTFILES=$1
fi

echo Installing dotfiles into $DOTFILES


link() {
    if [ -h ~/.$1 ]; then
        # symlink already exists but different, backup
        if [ "$(readlink ~/.$1)" != "$DOTFILES/files/$1" ]; then
            mv ~/.$1 ~/.$1.old
        else
            return 0
        fi
    elif [ -e ~/$1 ]; then
        # file/dir already exists. backup it and symlink to the new one
        mv ~/.$1 ~/.$1.old
    fi

    ln -s $DOTFILES/files/$1  ~/.$1 
    echo ~/.$1 linked
    return 0
}


linkall() {
    for each in $DOTFILES/files/*; do
        if [ -e $each ]; then
            link `basename $each` 
        fi
    done
    echo Dotfiles linked
    return 0
}

clone() {
    if ! [[ -d ~/.dotfiles ]]; then
        git clone git@github.com:riobard/dotfiles $DOTFILES
    else
        cd ~/.dotfiles
        git pull
    fi
    return 0
}

vim_vundle() {
    if ! [[ -d ~/.vim/bundle/vundle ]]; then
        git clone http://github.com/gmarik/vundle.git ~/.vim/bundle/vundle
    fi

    vi +BundleInstall +qall
    return 0
}


clone
linkall
vim_vundle
