set shell=/bin/bash\ -li " https://github.com/gmarik/vundle/issues/175
"set shellcmdflag=-ic       " use an interactive login shell for $PATH

set nocompatible
filetype off        " required to use Vundle

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" let Vundle manage Vundle (required!)
Bundle 'gmarik/vundle'

" GitHub repos
"Bundle 'nanotech/jellybeans.vim'
"Bundle 'plasticboy/vim-markdown'    " this one use filetype mkd, which is bad
"Bundle 'riobard/vim-cute-python'
"Bundle 'sickill/vim-monokai'
"Bundle 'tpope/vim-vividchalk'
Bundle 'Lokaltog/vim-powerline'
Bundle 'Townk/vim-autoclose'
Bundle 'adimit/prolog.vim'
Bundle 'altercation/vim-colors-solarized'
Bundle 'godlygeek/tabular'
Bundle 'jpalardy/vim-slime'
Bundle 'kchmck/vim-coffee-script'
Bundle 'kien/ctrlp.vim'
Bundle 'majutsushi/tagbar'
Bundle 'mileszs/ack.vim'
Bundle 'msanders/snipmate.vim'
Bundle 'nelstrom/vim-markdown-folding'
Bundle 'riobard/scala.vim'
Bundle 'scrooloose/nerdtree'
Bundle 'scrooloose/syntastic'
Bundle 'spolu/dwm.vim'
Bundle 'tomasr/molokai'
Bundle 'tpope/vim-fugitive'
Bundle 'tpope/vim-haml'
Bundle 'tpope/vim-markdown'
Bundle 'tpope/vim-repeat'

" Vim-scripts repos
Bundle 'surround.vim'
Bundle 'matchit.zip'
Bundle 'nginx.vim'
Bundle 'cocoa.vim'
Bundle 'applescript.vim'
Bundle 'httplog'
Bundle 'DrawIt'

filetype plugin indent on   " required by Vundle
